### ISSUE TITLE
Distribute binaries for easier usage

### ISSUE THREAD

**Issue by somini** [nelenkov/android-backup-extractor#68]
I took this repository to Gitlab and configured their CI system to produce binaries (the `build/libs/abe-all.jar` file produced by Gradle).

https://gitlab.com/somini/android-backup-extractor

The CI configuration is here, should be pretty simple: https://gitlab.com/somini/android-backup-extractor/blob/master/.gitlab-ci.yml

The binaries are available here: https://gitlab.com/somini/android-backup-extractor/-/jobs/artifacts/master/browse/build/libs?job=deploy

That link will always point to the latest correct build on the `master` branch.

**Comment by nelenkov** [comment]
Thanks. I've hesitated to provide binaries, since this small utility is not really straightforward to use, unless you have some programming experience, and thus can build/fix it yourself. CI makes releases easy, so I've added CI integration, inspired by your sample.

It looks like Github integrates better with Travis CI (free for OSS projects), so I've added a Travis config that pushes the latest binary to Github's releases page. I've also updated the README accordingly, so the binaries should be relatively easy to find.
